In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)
pd.set_option('display.max_colwidth', None)

In [2]:
df0 = pd.read_csv(r'C:\Users\meet.gajera\OneDrive\Desktop\hcdr__\Data\cleaned\application_cleaned.csv')

In [3]:
df0.head()

,SK_ID_CURR,TARGET,CODE_GENDER,DAYS_BIRTH,CNT_CHILDREN,CNT_FAM_MEMBERS,NAME_CONTRACT_TYPE,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_INCOME_TYPE,OCCUPATION_TYPE,OCCUPATION_TYPE_MISSING,ORGANIZATION_TYPE,DAYS_EMPLOYED,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,FLAG_OWN_CAR,FLAG_OWN_REALTY,NAME_HOUSING_TYPE,DAYS_LAST_PHONE_CHANGE,FLAG_EMAIL,FLAG_WORK_PHONE
0,100002,1,M,-9461,0,1.0,Cash loans,202500.0,406597.5,24700.5,351000.0,Working,Laborers,0,Business Entity Type 3,-637,Secondary / secondary special,Single / not married,N,Y,House / apartment,-1134.0,0,0
1,100003,0,F,-16765,0,2.0,Cash loans,270000.0,1293502.5,35698.5,1129500.0,State servant,Core staff,0,School,-1188,Higher education,Married,N,N,House / apartment,-828.0,0,0
2,100004,0,M,-19046,0,1.0,Revolving loans,67500.0,135000.0,6750.0,135000.0,Working,Laborers,0,Government,-225,Secondary / secondary special,Single / not married,Y,Y,House / apartment,-815.0,0,1
3,100006,0,F,-19005,0,2.0,Cash loans,135000.0,312682.5,29686.5,297000.0,Working,Laborers,0,Business Entity Type 3,-3039,Secondary / secondary special,Civil marriage,N,Y,House / apartment,-617.0,0,0
4,100007,0,M,-19932,0,1.0,Cash loans,121500.0,513000.0,21865.5,513000.0,Working,Core staff,0,Religion,-3038,Secondary / secondary special,Single / not married,N,Y,House / apartment,-1106.0,0,0

In [4]:
df = df0.copy()

In [5]:
df.shape

(307511, 24)

In [6]:
df['AGE'] = (-df['DAYS_BIRTH'] / 365).astype(int)

df['YEARS_EMPLOYED'] = round(abs(df['DAYS_EMPLOYED']) / 365, 2)

df['YEARS_CURRENT_PHONE'] = round(abs(df['DAYS_LAST_PHONE_CHANGE']) / 365, 2)

In [7]:
df.drop(
    columns=[
        'DAYS_BIRTH',
        'DAYS_EMPLOYED',
        'DAYS_LAST_PHONE_CHANGE'
    ],
    inplace=True
)

In [8]:
df.head()

,SK_ID_CURR,TARGET,CODE_GENDER,CNT_CHILDREN,CNT_FAM_MEMBERS,NAME_CONTRACT_TYPE,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_INCOME_TYPE,OCCUPATION_TYPE,OCCUPATION_TYPE_MISSING,ORGANIZATION_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,FLAG_OWN_CAR,FLAG_OWN_REALTY,NAME_HOUSING_TYPE,FLAG_EMAIL,FLAG_WORK_PHONE,AGE,YEARS_EMPLOYED,YEARS_CURRENT_PHONE
0,100002,1,M,0,1.0,Cash loans,202500.0,406597.5,24700.5,351000.0,Working,Laborers,0,Business Entity Type 3,Secondary / secondary special,Single / not married,N,Y,House / apartment,0,0,25,1.75,3.11
1,100003,0,F,0,2.0,Cash loans,270000.0,1293502.5,35698.5,1129500.0,State servant,Core staff,0,School,Higher education,Married,N,N,House / apartment,0,0,45,3.25,2.27
2,100004,0,M,0,1.0,Revolving loans,67500.0,135000.0,6750.0,135000.0,Working,Laborers,0,Government,Secondary / secondary special,Single / not married,Y,Y,House / apartment,0,1,52,0.62,2.23
3,100006,0,F,0,2.0,Cash loans,135000.0,312682.5,29686.5,297000.0,Working,Laborers,0,Business Entity Type 3,Secondary / secondary special,Civil marriage,N,Y,House / apartment,0,0,52,8.33,1.69
4,100007,0,M,0,1.0,Cash loans,121500.0,513000.0,21865.5,513000.0,Working,Core staff,0,Religion,Secondary / secondary special,Single / not married,N,Y,House / apartment,0,0,54,8.32,3.03

In [9]:
org_mapping = {
    #  Banking & Finance
    'Bank': 'Banking & Finance',
    'Insurance': 'Banking & Finance',

    #  Government & Public Sector
    'Government': 'Government',
    'Police': 'Government',
    'Military': 'Government',
    'Security Ministries': 'Government',
    'Emergency': 'Government',
    'Postal': 'Government',

    #  Education
    'School': 'Education',
    'University': 'Education',
    'Kindergarten': 'Education',

    #  Healthcare
    'Medicine': 'Healthcare',

    #  IT & Telecom
    'IT': 'IT & Telecom',
    'Telecom': 'IT & Telecom',
    'High skill tech staff': 'IT & Telecom',

    #  Construction & Real Estate
    'Construction': 'Construction',
    'Housing': 'Construction',
    'Realtor': 'Construction',

    #  Hospitality
    'Restaurant': 'Hospitality',
    'Hotel': 'Hospitality',

    #  Transport & Logistics
    'Transport: type 1': 'Transport',
    'Transport: type 2': 'Transport',
    'Transport: type 3': 'Transport',
    'Transport: type 4': 'Transport',

    #  Manufacturing & Industry
    'Industry: type 1': 'Manufacturing',
    'Industry: type 2': 'Manufacturing',
    'Industry: type 3': 'Manufacturing',
    'Industry: type 4': 'Manufacturing',
    'Industry: type 5': 'Manufacturing',
    'Industry: type 6': 'Manufacturing',
    'Industry: type 7': 'Manufacturing',
    'Industry: type 8': 'Manufacturing',
    'Industry: type 9': 'Manufacturing',
    'Industry: type 10': 'Manufacturing',
    'Industry: type 11': 'Manufacturing',
    'Industry: type 12': 'Manufacturing',
    'Industry: type 13': 'Manufacturing',
    'Electricity': 'Manufacturing',

    # Business & Corporate
    'Business Entity Type 1': 'Business & Corporate',
    'Business Entity Type 2': 'Business & Corporate',
    'Business Entity Type 3': 'Business & Corporate',
    'Advertising': 'Business & Corporate',
    'Legal Services': 'Business & Corporate',
    'Services': 'Business & Corporate',

    # Trade & Self-employed
    'Trade: type 1': 'Trade & Self-employed',
    'Trade: type 2': 'Trade & Self-employed',
    'Trade: type 3': 'Trade & Self-employed',
    'Trade: type 4': 'Trade & Self-employed',
    'Trade: type 5': 'Trade & Self-employed',
    'Trade: type 6': 'Trade & Self-employed',
    'Trade: type 7': 'Trade & Self-employed',
    'Self-employed': 'Trade & Self-employed',

    #  Other
    'Agriculture': 'Other',
    'Cleaning': 'Other',
    'Culture': 'Other',
    'Mobile': 'Other',
    'Other': 'Other',
    'Religion': 'Other',
    'Security': 'Other',
    'XNA': 'Other'
}

df['ORG_GROUP'] = (
    df['ORGANIZATION_TYPE']
      .map(org_mapping)
      .fillna('Other')
)

df.drop(columns=['ORGANIZATION_TYPE'], inplace=True)

In [10]:
df['CREDIT_INCOME_RATIO'] = np.where(
    df['AMT_INCOME_TOTAL'] > 0,
    df['AMT_CREDIT'] / df['AMT_INCOME_TOTAL'],
    0
).round(4)

In [11]:
df['ANNUITY_INCOME_RATIO'] = np.where(
    df['AMT_INCOME_TOTAL'] > 0,
    df['AMT_ANNUITY'] / df['AMT_INCOME_TOTAL'],
    0
).round(4)

In [12]:
df['CREDIT_ANNUITY_RATIO'] = np.where(
    df['AMT_ANNUITY'] > 0,
    df['AMT_CREDIT'] / df['AMT_ANNUITY'],
    0
).round(4)

In [13]:
df['GOODS_CREDIT_RATIO'] = np.where(
    df['AMT_CREDIT'] > 0,
    df['AMT_GOODS_PRICE'] / df['AMT_CREDIT'],
    0
).round(4)

In [14]:
df['INCOME_PER_FAM_MEMBER'] = np.where(
    df['CNT_FAM_MEMBERS'] > 0,
    df['AMT_INCOME_TOTAL'] / df['CNT_FAM_MEMBERS'],
    0
).round(4)

In [ ]:
df['EMPLOYMENT_AGE_RATIO'] = np.where(
    df['AGE'] > 0,
    df['YEARS_EMPLOYED'] / df['AGE'],
    0
).round(4)

In [16]:
df['NAME_FAMILY_STATUS'].value_counts()

NAME_FAMILY_STATUS
Married                 196432
Single / not married     45444
Civil marriage           29775
Separated                19770
Widow                    16088
Unknown                      2
Name: count, dtype: int64

In [17]:
df['IS_SINGLE_PARENT'] = (
                          (df['CNT_CHILDREN']>0) 
                          & 
                          (df['NAME_FAMILY_STATUS'].isin(['Married','Civil marriage']))
                          ).astype(int)

In [18]:
df['IS_SINGLE_PARENT'].value_counts()

IS_SINGLE_PARENT
0    228826
1     78685
Name: count, dtype: int64

In [19]:
df['HAS_DEPENDENTS'] = (df['CNT_CHILDREN'] > 0).astype(int)

In [20]:
df['HAS_DEPENDENTS'].value_counts()

HAS_DEPENDENTS
0    215371
1     92140
Name: count, dtype: int64

In [21]:
df.columns

Index(['SK_ID_CURR', 'TARGET', 'CODE_GENDER', 'CNT_CHILDREN',
       'CNT_FAM_MEMBERS', 'NAME_CONTRACT_TYPE', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY', 'AMT_GOODS_PRICE', 'NAME_INCOME_TYPE',
       'OCCUPATION_TYPE', 'OCCUPATION_TYPE_MISSING', 'NAME_EDUCATION_TYPE',
       'NAME_FAMILY_STATUS', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY',
       'NAME_HOUSING_TYPE', 'FLAG_EMAIL', 'FLAG_WORK_PHONE', 'AGE',
       'YEARS_EMPLOYED', 'YEARS_CURRENT_PHONE', 'ORG_GROUP',
       'CREDIT_INCOME_RATIO', 'ANNUITY_INCOME_RATIO', 'CREDIT_ANNUITY_RATIO',
       'GOODS_CREDIT_RATIO', 'INCOME_PER_FAM_MEMBER', 'EMPLOYMENT_AGE_RATIO',
       'IS_SINGLE_PARENT', 'HAS_DEPENDENTS'],
      dtype='object')

In [22]:
df.shape

(307511, 32)

In [23]:
df.sample(7)

,SK_ID_CURR,TARGET,CODE_GENDER,CNT_CHILDREN,CNT_FAM_MEMBERS,NAME_CONTRACT_TYPE,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_INCOME_TYPE,OCCUPATION_TYPE,OCCUPATION_TYPE_MISSING,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,FLAG_OWN_CAR,FLAG_OWN_REALTY,NAME_HOUSING_TYPE,FLAG_EMAIL,FLAG_WORK_PHONE,AGE,YEARS_EMPLOYED,YEARS_CURRENT_PHONE,ORG_GROUP,CREDIT_INCOME_RATIO,ANNUITY_INCOME_RATIO,CREDIT_ANNUITY_RATIO,GOODS_CREDIT_RATIO,INCOME_PER_FAM_MEMBER,EMPLOYMENT_AGE_RATIO,IS_SINGLE_PARENT,HAS_DEPENDENTS
89197,203563,0,F,0,1.0,Cash loans,202500.0,900000.0,23742.0,900000.0,Commercial associate,Unknown,1,Higher education,Widow,Y,N,House / apartment,0,1,54,12.26,0.01,Healthcare,4.4444,0.1172,37.9075,1.0000,202500.0,0.2270,0,0
288081,433728,0,M,1,3.0,Revolving loans,180000.0,495000.0,24750.0,495000.0,Working,High skill tech staff,0,Higher education,Married,N,Y,House / apartment,0,0,33,1.49,2.13,Business & Corporate,2.7500,0.1375,20.0000,1.0000,60000.0,0.0452,1,1
134804,256361,0,F,1,3.0,Cash loans,126000.0,358344.0,24075.0,283500.0,Commercial associate,Private service staff,0,Secondary / secondary special,Civil marriage,Y,Y,House / apartment,0,0,41,21.97,7.70,Business & Corporate,2.8440,0.1911,14.8845,0.7911,42000.0,0.5359,1,1
304003,452220,0,F,1,3.0,Cash loans,135000.0,298512.0,23715.0,270000.0,Working,Unknown,1,Secondary / secondary special,Civil marriage,N,Y,House / apartment,0,0,28,4.49,1.79,Business & Corporate,2.2112,0.1757,12.5875,0.9045,45000.0,0.1604,1,1
93544,208628,0,F,0,1.0,Cash loans,112500.0,239850.0,23494.5,225000.0,Pensioner,Unknown,1,Secondary / secondary special,Single / not married,N,Y,House / apartment,0,0,67,1000.67,4.15,Other,2.1320,0.2088,10.2088,0.9381,112500.0,14.9354,0,0
32247,137389,0,F,0,2.0,Cash loans,144000.0,1056447.0,31018.5,922500.0,Pensioner,Unknown,1,Secondary / secondary special,Married,Y,Y,House / apartment,0,0,49,1000.67,8.79,Other,7.3364,0.2154,34.0586,0.8732,72000.0,20.4218,0,0
135798,257503,0,F,0,2.0,Cash loans,157500.0,876154.5,44865.0,769500.0,Working,Accountants,0,Higher education,Civil marriage,N,N,With parents,0,0,36,0.55,5.46,Business & Corporate,5.5629,0.2849,19.5287,0.8783,78750.0,0.0153,0,0

In [24]:
# saving featured csv

df.to_csv(r"C:\Users\meet.gajera\OneDrive\Desktop\hcdr__\Data\featured\application_featured.csv", index=False)