In [76]:
import pandas as pd
import numpy as np
import seaborn as sns

pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)
pd.set_option('display.max_colwidth', None)

In [77]:
df0 = pd.read_csv(r'C:\Users\meet.gajera\OneDrive\Desktop\HCDR\Data\cleaned\application_cleaned.csv')

In [78]:
df0.head()

,SK_ID_CURR,TARGET,CODE_GENDER,DAYS_BIRTH,CNT_CHILDREN,CNT_FAM_MEMBERS,NAME_CONTRACT_TYPE,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_ANNUITY_trans,AMT_GOODS_PRICE,AMT_GOODS_PRICE_trans,NAME_INCOME_TYPE,OCCUPATION_TYPE,OCCUPATION_TYPE_MISSING,ORGANIZATION_TYPE,DAYS_EMPLOYED,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,FLAG_OWN_CAR,FLAG_OWN_REALTY,NAME_HOUSING_TYPE,DAYS_LAST_PHONE_CHANGE,FLAG_EMAIL,FLAG_WORK_PHONE
0,100002,1,M,-9461,0,1.0,Cash loans,202500.0,406597.5,24700.5,10.114619,351000.0,12.768544,Working,Laborers,0,Business Entity Type 3,-637,Secondary / secondary special,Single / not married,N,Y,House / apartment,-1134.0,0,0
1,100003,0,F,-16765,0,2.0,Cash loans,270000.0,1293502.5,35698.5,10.482892,1129500.0,13.937287,State servant,Core staff,0,School,-1188,Higher education,Married,N,N,House / apartment,-828.0,0,0
2,100004,0,M,-19046,0,1.0,Revolving loans,67500.0,135000.0,6750.0,8.817446,135000.0,11.813037,Working,Laborers,0,Government,-225,Secondary / secondary special,Single / not married,Y,Y,House / apartment,-815.0,0,1
3,100006,0,F,-19005,0,2.0,Cash loans,135000.0,312682.5,29686.5,10.298481,297000.0,12.601491,Working,Laborers,0,Business Entity Type 3,-3039,Secondary / secondary special,Civil marriage,N,Y,House / apartment,-617.0,0,0
4,100007,0,M,-19932,0,1.0,Cash loans,121500.0,513000.0,21865.5,9.992711,513000.0,13.148033,Working,Core staff,0,Religion,-3038,Secondary / secondary special,Single / not married,N,Y,House / apartment,-1106.0,0,0

In [79]:
df = df0.copy()

In [80]:
df.shape

(307511, 26)

In [81]:
df['AGE'] = (-df['DAYS_BIRTH'] / 365).astype(int)

df['YEARS_EMPLOYED'] = round(abs(df['DAYS_EMPLOYED']) / 365, 2)

df['YEARS_CURRENT_PHONE'] = round(abs(df['DAYS_LAST_PHONE_CHANGE']) / 365, 2)

In [82]:
df.drop(
    columns=[
        'DAYS_BIRTH',
        'DAYS_EMPLOYED',
        'DAYS_LAST_PHONE_CHANGE'
    ],
    inplace=True
)

In [83]:
df.head()

,SK_ID_CURR,TARGET,CODE_GENDER,CNT_CHILDREN,CNT_FAM_MEMBERS,NAME_CONTRACT_TYPE,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_ANNUITY_trans,AMT_GOODS_PRICE,AMT_GOODS_PRICE_trans,NAME_INCOME_TYPE,OCCUPATION_TYPE,OCCUPATION_TYPE_MISSING,ORGANIZATION_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,FLAG_OWN_CAR,FLAG_OWN_REALTY,NAME_HOUSING_TYPE,FLAG_EMAIL,FLAG_WORK_PHONE,AGE,YEARS_EMPLOYED,YEARS_CURRENT_PHONE
0,100002,1,M,0,1.0,Cash loans,202500.0,406597.5,24700.5,10.114619,351000.0,12.768544,Working,Laborers,0,Business Entity Type 3,Secondary / secondary special,Single / not married,N,Y,House / apartment,0,0,25,1.75,3.11
1,100003,0,F,0,2.0,Cash loans,270000.0,1293502.5,35698.5,10.482892,1129500.0,13.937287,State servant,Core staff,0,School,Higher education,Married,N,N,House / apartment,0,0,45,3.25,2.27
2,100004,0,M,0,1.0,Revolving loans,67500.0,135000.0,6750.0,8.817446,135000.0,11.813037,Working,Laborers,0,Government,Secondary / secondary special,Single / not married,Y,Y,House / apartment,0,1,52,0.62,2.23
3,100006,0,F,0,2.0,Cash loans,135000.0,312682.5,29686.5,10.298481,297000.0,12.601491,Working,Laborers,0,Business Entity Type 3,Secondary / secondary special,Civil marriage,N,Y,House / apartment,0,0,52,8.33,1.69
4,100007,0,M,0,1.0,Cash loans,121500.0,513000.0,21865.5,9.992711,513000.0,13.148033,Working,Core staff,0,Religion,Secondary / secondary special,Single / not married,N,Y,House / apartment,0,0,54,8.32,3.03

In [84]:
org_mapping = {
    #  Banking & Finance
    'Bank': 'Banking & Finance',
    'Insurance': 'Banking & Finance',

    #  Government & Public Sector
    'Government': 'Government',
    'Police': 'Government',
    'Military': 'Government',
    'Security Ministries': 'Government',
    'Emergency': 'Government',
    'Postal': 'Government',

    #  Education
    'School': 'Education',
    'University': 'Education',
    'Kindergarten': 'Education',

    #  Healthcare
    'Medicine': 'Healthcare',

    #  IT & Telecom
    'IT': 'IT & Telecom',
    'Telecom': 'IT & Telecom',
    'High skill tech staff': 'IT & Telecom',

    #  Construction & Real Estate
    'Construction': 'Construction',
    'Housing': 'Construction',
    'Realtor': 'Construction',

    #  Hospitality
    'Restaurant': 'Hospitality',
    'Hotel': 'Hospitality',

    #  Transport & Logistics
    'Transport: type 1': 'Transport',
    'Transport: type 2': 'Transport',
    'Transport: type 3': 'Transport',
    'Transport: type 4': 'Transport',

    #  Manufacturing & Industry
    'Industry: type 1': 'Manufacturing',
    'Industry: type 2': 'Manufacturing',
    'Industry: type 3': 'Manufacturing',
    'Industry: type 4': 'Manufacturing',
    'Industry: type 5': 'Manufacturing',
    'Industry: type 6': 'Manufacturing',
    'Industry: type 7': 'Manufacturing',
    'Industry: type 8': 'Manufacturing',
    'Industry: type 9': 'Manufacturing',
    'Industry: type 10': 'Manufacturing',
    'Industry: type 11': 'Manufacturing',
    'Industry: type 12': 'Manufacturing',
    'Industry: type 13': 'Manufacturing',
    'Electricity': 'Manufacturing',

    # Business & Corporate
    'Business Entity Type 1': 'Business & Corporate',
    'Business Entity Type 2': 'Business & Corporate',
    'Business Entity Type 3': 'Business & Corporate',
    'Advertising': 'Business & Corporate',
    'Legal Services': 'Business & Corporate',
    'Services': 'Business & Corporate',

    # Trade & Self-employed
    'Trade: type 1': 'Trade & Self-employed',
    'Trade: type 2': 'Trade & Self-employed',
    'Trade: type 3': 'Trade & Self-employed',
    'Trade: type 4': 'Trade & Self-employed',
    'Trade: type 5': 'Trade & Self-employed',
    'Trade: type 6': 'Trade & Self-employed',
    'Trade: type 7': 'Trade & Self-employed',
    'Self-employed': 'Trade & Self-employed',

    #  Other
    'Agriculture': 'Other',
    'Cleaning': 'Other',
    'Culture': 'Other',
    'Mobile': 'Other',
    'Other': 'Other',
    'Religion': 'Other',
    'Security': 'Other',
    'XNA': 'Other'
}

df['ORG_GROUP'] = (
    df['ORGANIZATION_TYPE']
      .map(org_mapping)
      .fillna('Other')
)

df.drop(columns=['ORGANIZATION_TYPE'], inplace=True)

In [85]:
df['CRDIT_INCOME_RATIO'] = round(df['AMT_CREDIT']/df['AMT_INCOME_TOTAL'], 4)

In [86]:
df['ANNUITY_INCOME_RATIO'] = round(df['AMT_ANNUITY']/df['AMT_INCOME_TOTAL'], 4)

In [87]:
df['CREDIT_ANNUITY_RATIO'] = round(df['AMT_CREDIT']/df['AMT_ANNUITY'], 4)

In [88]:
df['GOODS_CREDIT_RATIO'] = round(df['AMT_GOODS_PRICE']/df['AMT_CREDIT'], 4)

In [89]:
df['INCOME_PER_FAM_MEMBER'] = round(df['AMT_INCOME_TOTAL']/df['CNT_FAM_MEMBERS'], 4)

In [90]:
df['EMPLOYMENT_AGE_RATIO'] = round(df['YEARS_EMPLOYED']/df['AGE'], 4)

In [91]:
df['NAME_FAMILY_STATUS'].value_counts()

NAME_FAMILY_STATUS
Married                 196432
Single / not married     45444
Civil marriage           29775
Separated                19770
Widow                    16088
Unknown                      2
Name: count, dtype: int64

In [92]:
df['IS_SINGLE_PARENT'] = (
                          (df['CNT_CHILDREN']>0) 
                          & 
                          (df['NAME_FAMILY_STATUS'].isin(['Married','Civil marriage']))
                          ).astype(int)

In [93]:
df['IS_SINGLE_PARENT'].value_counts()

IS_SINGLE_PARENT
0    228826
1     78685
Name: count, dtype: int64

In [94]:
df['HAS_DEPENDENTS'] = (df['CNT_CHILDREN'] > 0).astype(int)

In [95]:
df['HAS_DEPENDENTS'].value_counts()

HAS_DEPENDENTS
0    215371
1     92140
Name: count, dtype: int64

In [96]:
df.columns

Index(['SK_ID_CURR', 'TARGET', 'CODE_GENDER', 'CNT_CHILDREN',
       'CNT_FAM_MEMBERS', 'NAME_CONTRACT_TYPE', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY', 'AMT_ANNUITY_trans', 'AMT_GOODS_PRICE',
       'AMT_GOODS_PRICE_trans', 'NAME_INCOME_TYPE', 'OCCUPATION_TYPE',
       'OCCUPATION_TYPE_MISSING', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS',
       'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'NAME_HOUSING_TYPE', 'FLAG_EMAIL',
       'FLAG_WORK_PHONE', 'AGE', 'YEARS_EMPLOYED', 'YEARS_CURRENT_PHONE',
       'ORG_GROUP', 'CRDIT_INCOME_RATIO', 'ANNUITY_INCOME_RATIO',
       'CREDIT_ANNUITY_RATIO', 'GOODS_CREDIT_RATIO', 'INCOME_PER_FAM_MEMBER',
       'EMPLOYMENT_AGE_RATIO', 'IS_SINGLE_PARENT', 'HAS_DEPENDENTS'],
      dtype='object')

In [97]:
df.shape

(307511, 34)

In [98]:
df.sample(7)

,SK_ID_CURR,TARGET,CODE_GENDER,CNT_CHILDREN,CNT_FAM_MEMBERS,NAME_CONTRACT_TYPE,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_ANNUITY_trans,AMT_GOODS_PRICE,AMT_GOODS_PRICE_trans,NAME_INCOME_TYPE,OCCUPATION_TYPE,OCCUPATION_TYPE_MISSING,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,FLAG_OWN_CAR,FLAG_OWN_REALTY,NAME_HOUSING_TYPE,FLAG_EMAIL,FLAG_WORK_PHONE,AGE,YEARS_EMPLOYED,YEARS_CURRENT_PHONE,ORG_GROUP,CRDIT_INCOME_RATIO,ANNUITY_INCOME_RATIO,CREDIT_ANNUITY_RATIO,GOODS_CREDIT_RATIO,INCOME_PER_FAM_MEMBER,EMPLOYMENT_AGE_RATIO,IS_SINGLE_PARENT,HAS_DEPENDENTS
20866,124317,0,F,2,4.0,Cash loans,94500.0,219870.0,9814.5,9.191718,157500.0,11.967187,Working,Unknown,1,Secondary / secondary special,Civil marriage,N,N,House / apartment,0,0,39,2.04,0.99,Manufacturing,2.3267,0.1039,22.4026,0.7163,23625.0,0.0523,1,1
180402,309076,0,M,0,2.0,Cash loans,270000.0,877500.0,25785.0,10.157587,877500.0,13.684833,Working,Unknown,1,Secondary / secondary special,Married,Y,Y,House / apartment,0,0,46,1.69,8.87,Construction,3.2500,0.0955,34.0314,1.0000,135000.0,0.0367,0,0
258439,399077,0,F,0,2.0,Cash loans,112500.0,112068.0,11898.0,9.384210,99000.0,11.502885,Commercial associate,Laborers,0,Secondary / secondary special,Married,N,Y,Municipal apartment,0,0,52,11.33,8.99,Trade & Self-employed,0.9962,0.1058,9.4191,0.8834,56250.0,0.2179,0,0
122610,242150,0,F,2,4.0,Cash loans,112500.0,1078200.0,28570.5,10.260165,900000.0,13.710151,Working,Sales staff,0,Higher education,Married,N,N,House / apartment,0,0,26,2.64,4.17,Business & Corporate,9.5840,0.2540,37.7382,0.8347,28125.0,0.1015,1,1
264394,406196,1,F,0,2.0,Cash loans,225000.0,906228.0,38524.5,10.559076,810000.0,13.604791,Pensioner,Unknown,1,Secondary / secondary special,Married,N,Y,House / apartment,0,0,55,1000.67,4.60,Other,4.0277,0.1712,23.5234,0.8938,112500.0,18.1940,0,0
90267,204795,0,F,0,2.0,Cash loans,67500.0,472500.0,13815.0,9.533583,472500.0,13.065795,Pensioner,Unknown,1,Secondary / secondary special,Married,N,N,House / apartment,0,0,63,1000.67,4.87,Other,7.0000,0.2047,34.2020,1.0000,33750.0,15.8837,0,0
54028,162598,0,M,2,4.0,Cash loans,382500.0,254700.0,28867.5,10.270506,225000.0,12.323860,Working,Laborers,0,Secondary / secondary special,Married,Y,Y,House / apartment,0,0,39,4.62,0.00,Business & Corporate,0.6659,0.0755,8.8231,0.8834,95625.0,0.1185,1,1

In [99]:
# saving featured csv

df.to_csv(r"C:\Users\meet.gajera\OneDrive\Desktop\HCDR\Data\featured\application_featured.csv", index=False)